apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: iphone-app
  name: iphone-app
spec:
  containers:
  - image: azotamiota/iphone-shop-app:4.0.7
    name: iphone-app
    resources: {}
    ports:
    - containerPort: 5000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: iphone-app
  name: iphone-app-service
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 5000
  selector:
    run: iphone-app
  type: NodePort
