name: Phone Shop Web App CI/CD

on:
  push:
    branches:
      - main
      - feat*
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # env:
    #   COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Import GPG Key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          echo "GPG key imported successfully"

      - name: Decrypt Secrets
        run: ./secrets/decrypt_secrets.sh

      - name: Build Docker Image
        run: ./scripts/docker_action.sh build "${{ github.sha }}" "${{ github.ref }}" "${{ github.event_name }}" "${{ vars.DOCKERHUB_USERNAME }}"

      - name: Push Docker Image
        run: ./scripts/docker_action.sh push ${{ github.sha }} ${{ github.ref }} ${{ github.event_name }} ${{ vars.DOCKERHUB_USERNAME }}
